In [58]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

In [40]:
data = {
    'name': ['adarsh','akash','atharva','jay','neeraj'],
    'age': [20,23,None,43,None],
    'salary': [10000,20000,None,40000,40000]
}
df = pd.DataFrame(data)

In [41]:
df.count()

name      5
age       3
salary    4
dtype: int64

In [42]:
df.isna().sum()

name      0
age       2
salary    1
dtype: int64

In [43]:
df[df['age'].isnull()]

name  age   salary
2  atharva  NaN      NaN
4   neeraj  NaN  40000.0

In [44]:
mean_age = df['age'].mean()
print(round(mean_age,0))
mean_sal = df['salary'].mean()
print(round(mean_sal))

29.0
27500


In [45]:
df = df.fillna(
    {'age' : mean_age,
    'salary' : mean_sal}
)
df

name        age   salary
0   adarsh  20.000000  10000.0
1    akash  23.000000  20000.0
2  atharva  28.666667  27500.0
3      jay  43.000000  40000.0
4   neeraj  28.666667  40000.0

In [29]:
# Lets do one hot code 

In [46]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

One_hot_encoder = OneHotEncoder()
encoded_data = One_hot_encoder.fit_transform(df[['name']])
print(encoded_data.toarray())


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [47]:
encoded_df = pd.DataFrame(encoded_data.toarray(), columns=One_hot_encoder.get_feature_names_out(['name']))
df = df.join(encoded_df).drop(columns=['name'])

In [48]:
df

age   salary  name_adarsh  name_akash  name_atharva  name_jay  \
0  20.000000  10000.0          1.0         0.0           0.0       0.0   
1  23.000000  20000.0          0.0         1.0           0.0       0.0   
2  28.666667  27500.0          0.0         0.0           1.0       0.0   
3  43.000000  40000.0          0.0         0.0           0.0       1.0   
4  28.666667  40000.0          0.0         0.0           0.0       0.0   

   name_neeraj  
0          0.0  
1          0.0  
2          0.0  
3          0.0  
4          1.0

In [50]:
X = df.drop(columns=['salary'])
y = df['salary']

In [52]:
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=25)

In [55]:
model = LinearRegression()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)

In [61]:
print("mse: ", mean_squared_error(y_test,y_pred))
print("r2_score: ", r2_score(y_test,y_pred))

mse:  377330625.0
r2_score:  nan


/Users/adarshbadjate/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)


In [59]:
model = RandomForestRegressor()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)


In [60]:
print("mse_rfr: ", mean_squared_error(y_test,y_pred))
print("r2_score_rfr: ", r2_score(y_test,y_pred))

mse_rfr:  377330625.0
r2_score_rfr:  nan


/Users/adarshbadjate/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)


In [ ]:
new_instance = pd.DataFrame({'name': ['adarsh'], 'age': [25]})
